config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "queries#index"
  resources :eviction_notices, only: [:index, :show]

  resources :queries, only: [:index, :show, :create]
  post "/run_query" => "queries#run_query"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_source.rb
class DataSource < ApplicationRecord
end

app/models/eviction_notice.rb
require "elasticsearch/model"

class EvictionNotice < ApplicationRecord
  include Elasticsearch::Model
end

app/models/police_incident.rb
class PoliceIncident < ApplicationRecord
  validates :incident_number, numericality: true
  validates :category, presence: true
  validates :description, presence: true

  validates :day_of_week, inclusion: { in: %w(Monday Tuesday Wednesday Thursday Friday Saturday Sunday), message: "%{value} must be a day of the week" }
  validates :date, presence: true
  validates :time, presence: true
  validates :address, presence: true

  validates :police_department_district_id, numericality: true
  validates :police_department_district_name, presence: true
  validates :resolution, presence: true

  validates :x_coordinate, presence: true
  validates :y_coordinate, presence: true
end

app/models/query.rb
class Query < ApplicationRecord
  INVALID_SQL = ["alter", "drop", "delete"]

  def execute_query
    if query_contains_ddl
      invalid_query_error_instance_vars("DDL statements such as #{Query::INVALID_SQL.join(', ')} cannot be executed.")
    else
      begin
        results = ActiveRecord::Base.connection.exec_query(query)
      rescue Exception => e
        ActiveRecord::Base.connection.execute "ROLLBACK"
        invalid_query_error_instance_vars(e.message)
      end
    end

    results
  end

  def query_contains_ddl
    INVALID_SQL.any?{ |invalid| query.include?(invalid) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  protect_from_forgery except: :index

  def index
    @queries = Query.all
    @new_query = Query.new
  end

  def show
    @running_query = Query.find(params[:id])
    @results = @running_query.execute_query
    @new_query = Query.new
  end

  def create
    @query_to_save = Query.new(query_params)

    if @query_to_save.query_contains_ddl
      invalid_query_error_instance_vars("#{Query::INVALID_SQL.join(', ')} statements cannot be saved.")
    else
      begin
        ActiveRecord::Base.connection.exec_query(query_params[:query])
      rescue Exception => e
        ActiveRecord::Base.connection.execute "ROLLBACK"
        invalid_query_error_instance_vars(e.message)
      else
        if @query_to_save.save!
          redirect_to query_path(@query_to_save)
        else
          @new_query = Query.new(query_params)
          render :index, notice: "Query could not be saved!"
        end
      end
    end
  end

  def run_query
    if params[:commit] == "Run query"
      @running_query = Query.new(query_params)
    else
      @running_query = Query.find(params[:query][:id])
    end

    if @running_query.query_contains_ddl
      invalid_query_error_instance_vars("#{Query::INVALID_SQL.join(', ')} statements cannot be run.")
    else
      begin
        results = ActiveRecord::Base.connection.exec_query(@running_query.query)
      rescue Exception => e
        ActiveRecord::Base.connection.execute "ROLLBACK"
        invalid_query_error_instance_vars(e.message)
      else
        @new_query = Query.new
        @results = results
        render :show
      end
    end
  end

  private

  def query_params
    params.require(:query).permit(:query)
  end

  def invalid_query_error_instance_vars(error_message)
    flash[:notice] = error_message
    @new_query = Query.new(query_params)
    @queries = Query.all
    render :index
  end

  def clean_up_query
    # remove \t and \n
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/eviction_notices/_eviction_notices.erb
<table>
  <thead>
    <tr>
        <th>eviction_id</th>
        <th>address</th>
        <th>file_date</th>
        <th>supervisor_district</th>
        <th>non_payment</th>
        <th>illegal_use</th>
        <th>location</th>
        <th>neighborhoods___analysis_boundaries</th>
    </tr>
  </thead>
  <tbody>
    <% evictions.each do |eviction| %>
      <tr>
        <td><%= eviction.eviction_id %></td>
        <td><%= eviction.address %></td>
        <td><%= eviction.file_date %></td>
        <td><%= eviction.supervisor_district %></td>
        <td><%= eviction.non_payment %></td>
        <td><%= eviction.illegal_use %></td>
        <td><%= eviction.location %></td>
        <td><%= eviction.neighborhoods___analysis_boundaries %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if evictions.any? %>
  <%= link_to_prev_page evictions, 'Previous Page' %>
  <%= link_to_next_page evictions, 'Next Page' %>
<% end %>

app/views/eviction_notices/index.erb
<h4>Eviction Notices</h4>

<h5>Query</h5>

<% if flash.notice %>
  <div style="color: red;margin: 10px 0px;"><%= flash.notice %></div>
<% end %>

<%= form_tag('/eviction_notices/run_query', method: :post) do %>
  <%= text_area_tag :query, @query.query %>
  <%= submit_tag "Run query" %>

  <% if flash.notice %>
    <%= submit_tag "Save query", hidden: true %>
  <% else %>
    <%= submit_tag "Save query", formaction: queries_path(@query) %>
  <% end %>
<% end %>

<%= render partial: 'eviction_notices/eviction_notices', locals: { evictions: @evictions} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SfPoliceData</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <div class="brand-logo">
          <%= link_to "Home", root_path =%>
        </div>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="sass.html">Sass</a></li>
          <li><a href="badges.html">Components</a></li>
          <li><a href="collapsible.html">JavaScript</a></li>
        </ul>
      </div>
    </nav>

    <div style="margin: 2% 5%">
      <%= yield %>
    </div>

    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Footer Content</h5>
            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/queries/_new_query.erb
<h5>New Query</h5>

<% if flash.notice %>
  <div style="color: red;margin: 10px 0px;"><%= flash.notice %></div>
<% end %>

<%= form_for @new_query, url: run_query_path do |f| %>
  <%= f.text_area :query %>
  <%= f.submit "Run query", name: "commit" %>

  <% if flash.notice %>
    <%= f.submit "Save query", hidden: true %>
  <% else %>
    <%= f.submit "Save query", formaction: queries_path(@new_query) %>
  <% end %>
<% end %>

app/views/queries/index.erb
<h4>Queries</h4>

<%= render partial: 'new_query', locals: { new_query: Query.new } %>

<table>
  <thead>
    <tr>
        <th>id</th>
        <th>query</th>
        <th>created_at</th>
        <th>updated_at</th>
    </tr>
  </thead>
  <tbody>
    <% @queries.each do |query| %>
      <tr>
        <td><%= query.id %></td>
        <td><%= link_to query.query, run_query_path(query: { id: query.id }, commit: "persisted_query"), method: :post %></td>
        <td><%= query.created_at %></td>
        <td><%= query.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/queries/show.erb
<h4>Query Results</h4>
<i><%= @running_query.query %></i>

<table class="responsive-table striped">
  <thead>
    <tr>
      <% @results.columns.each do |col_name| %>
        <th><%= col_name %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @results.rows.each do |row| %>
      <tr>
        <% row.each do |value| %>
          <td><%= value %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: 'new_query', locals: { new_query: Query.new } %>